#!/usr/bin/env bash
# display descriptions about the domain/subdomain entered
subdomain () {
    sub=$(echo "$1" | awk -F "." '{print $1}')
    record=$(dig "$1" | grep -A1 'ANSWER SECTION:' | awk 'NR>1' | awk -F ' ' '{print $4}')
    destination=$(dig $1 | grep -A1 'ANSWER SECTION:' | awk 'NR>1' | awk -F ' ' '{print $5}')
    echo "The subdomain $sub is a $record record and points to $destination"
}
domain () {
    subdomain "www.$1"
    subdomain "lb-01.$1"
    subdomain "web-01.$1"
    subdomain "web-02.$1"
}

check_subdomain () {
    if [[ "$1" == *.*.* ]]
    then
        res="sub"
    elif [[ "$1" == *.* ]]
    then
        res="dom"
    fi
}
check_subdomain "$1"
if [ $# -eq 2 ]
then
    subdomain "$2.$1"
elif [ "$res" == "dom" ]
then
    domain $1
else
    subdomain $1
fi
