#!/usr/bin/env bash
#redirect permanently
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "25i $str" /etc/nginx/sites-available/default
sudo service nginx reload
