#!/usr/bin/env bash
#redirect permanently
apt-get -y update
apt-get -y install nginx
systemctl restart nginx
sed -i "/^[[:space:]]# SSL configuration$/i rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
