#!/usr/bin/env bash
#redirect permanently
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404lol.html
newlines="\\\terror_page 404 /404lol.html;\n\tlocation = /404lol.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n}"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
sudo service nginx reload
