#!/usr/bin/env bash
#configuring a new machine, install nginx and configure it
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
#--
str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "25i $str" /etc/nginx/sites-available/default
sudo service nginx reload
#--
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404lol.html
newlines="\\\terror_page 404 /404lol.html;\n\tlocation = /404lol.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n}"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
#--
new="\\\tadd_header X-Served-By $(hostname);"
sudo sed -i "26i $new" /etc/nginx/sites-available/default
sudo service nginx reload
