#!/usr/bin/env bash
#configuring a new machine, install nginx and configure it
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
#--
new="\\\tadd_header X-Served-By $(hostname);"
sudo sed -i "26i $new" /etc/nginx/sites-available/default
sudo service nginx reload
