#!/usr/bin/env bash
#enable dedicated ppa
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "listen 1079-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1079-web-01 3.91.44.133:80 check\n\tserver 1079-web-02 35.227.49.226:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
