#!/usr/bin/env bash
#displays Holberton School 8 times, Hi one time and then Holberton school one time
declare -i i
i=0
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	i=$i+1
done
