#!/usr/bin/env bash
# counts to 20, after each bad luck number, the country's bad luck day name is displayed on screen
declare -i i
i=1
while [ $i -le 20 ]
do
	echo $i
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	i=$i+1
done
