#!/usr/bin/env bash
# counts to 20, after each bad luck number, the country's bad luck day name is displayed on screen
declare -i i
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in 
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	i=$i+1
done
