#!/usr/bin/env bash
#enable dedicated ppa
apt-get update
sudo apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
#install
apt-get update
sudo apt-get install haproxy=2.0.\*
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo sed -i "$ a\listen 1079-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1079-web-01 3.91.44.133 check\n\tserver 1079-web-02 35.227.49.226 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
